name: Docker Build

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      # Converter o nome do repositório para lowercase
      - name: Convert to lowercase
        id: convert
        run: |
          lower_name=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "lower_name=${lower_name}" >> $GITHUB_ENV

      # Fazer checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Fazer login no GitHub Container Registry
      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Construir e enviar a imagem para amd64
      - name: Build the Docker Image for amd64
        run: |
          docker buildx create --use # Cria o builder se não existir
          docker buildx build --platform linux/amd64 -t ghcr.io/${{ env.lower_name }}:latest . --push

      # Construir e enviar a imagem para arm64
      - name: Build the Docker Image for arm64
        run: |
          docker buildx build --platform linux/arm64 -t ghcr.io/${{ env.lower_name }}:latest . --push

      # Construir e enviar a imagem com a tag da versão para amd64
      - name: Build the Docker Image Version for amd64
        run: |
          docker buildx build --platform linux/amd64 -t ghcr.io/${{ env.lower_name }}:${{ github.ref_name }} . --push

      # Construir e enviar a imagem com a tag da versão para arm64
      - name: Build the Docker Image Version for arm64
        run: |
          docker buildx build --platform linux/arm64 -t ghcr.io/${{ env.lower_name }}:${{ github.ref_name }} . --push
